create table sensors
(
    sensor_id  int primary key generated by default as identity,
    name       varchar(100) unique not null,
    type       varchar(100)        not null,
    created_at timestamp           not null
);

CREATE TABLE measurements
(
    measurement_id int primary key generated by default as identity,
    sensor_id      int                                                       references sensors (sensor_id) on delete set null,
    value          double precision check ( value <= 100 and value >= -100 ) not null,
    raining        boolean                                                   not null,
    created_at     timestamp                                                 not null
);

